project:
  type: website
  
website: 
  title: "Práctica de Visualizar y Transformar de R4DS"
  favicon: favicon.ico
  sidebar: 
    style: docked
    contents: 
      - index.qmd
      - section: "Visualización"
        contents: 
        - analysis/9-capas.qmd
        - analysis/10-eda.qmd
        - analysis/11-comunicar.qmd
      - section: "Transformar"
        contents: 
        - analysis/12-vectores-logicos.qmd
        - analysis/13-numeros.qmd
  
  page-footer:
    left: "Copyright 2026, COVSAcorp"
    right: 
    - icon: github
      href: https://github.com/
    - icon: twitter
      href: https://twitter.com/
    
format:
  html: 
    theme: cosmo
    toc: true